from mongoengine import DynamicDocument, StringField, BooleanField, DictField, ListField, IntField, FloatField


class ProductUrls(DynamicDocument):
    meta = {"db_alias": "default"}
    unique_id = StringField()
    name = StringField()
    pdp_url = StringField()
    brand = StringField()
    price = StringField()
    price_per_unit = StringField()
    image_url = StringField()

class ProductItems(DynamicDocument):
    meta = {"db_alias": "default"}
    unique_id = StringField()
    competitor_name = StringField()
    extraction_date = StringField()
    product_name = StringField()
    brand = StringField()
    grammage_quantity = StringField()
    grammage_unit = StringField()
    producthierarchy_level1 = StringField()
    producthierarchy_level2 = StringField()
    producthierarchy_level3 = StringField()
    producthierarchy_level4 = StringField()
    producthierarchy_level5 = StringField()
    producthierarchy_level6 = StringField()
    regular_price = StringField()
    selling_price = StringField()
    promotion_description = StringField()
    currency = StringField()
    breadcrumb = StringField()
    pdp_url = StringField()
    product_description = StringField()
    storage_instructions = StringField()
    instructionforuse = StringField()
    allergens = StringField()
    country_of_origin = StringField()
    image_url_1 = StringField()
    image_url_2 = StringField()
    image_url_3 = StringField()
    image_url_4 = StringField()
    image_url_5 = StringField()
    image_url_6= StringField()
    nutritional_informations = DictField()
    special_infomation = StringField()
    food_preservation = StringField()
    manufacturer_address = StringField()
    site_shown_uom = StringField()
    ingredients = StringField()
    instock = BooleanField()
    product_unique_key = StringField()

